/**
 * Tree mesh loader — loads pre-generated GLB tree meshes via 3D Tilesets.
 *
 * Tree meshes are generated by extract_scene_dae.py, converted to GLB,
 * and wrapped in tileset.json for correct geopositioning.
 * Each tileset covers one 512m VegLiDAR tile.
 */
const Trees = {
    TILE_BASE: new URLSearchParams(window.location.search).get('tileBase') || 'data/tree_tiles/',
    tileIndex: null,
    loadedTiles: new Set(),
    tilesets: [],
    heightOffset: -6, // meters — compensates for canopy start height + terrain model gap

    TILE_SIZE_M: 512,

    async loadIndex() {
        try {
            const resp = await fetch(this.TILE_BASE + 'index.json');
            this.tileIndex = await resp.json();
            console.log(`Tree tile index: ${Object.keys(this.tileIndex.tiles).length} tiles available`);
            return this.tileIndex;
        } catch (e) {
            console.warn('No tree tile index found — tree meshes not available');
            this.tileIndex = { tiles: {} };
            return this.tileIndex;
        }
    },

    getTilesForLocation(lat, lng, radiusM) {
        if (!this.tileIndex) return [];
        // Filter tiles by distance — use search radius + one tile width for overlap
        const maxDistM = radiusM + 512;
        const matching = [];
        for (const [name, info] of Object.entries(this.tileIndex.tiles)) {
            const dLat = (info.center_lat - lat) * 111000;
            const dLng = (info.center_lng - lng) * 111000 * Math.cos(lat * Math.PI / 180);
            const dist = Math.sqrt(dLat * dLat + dLng * dLng);
            if (dist < maxDistM) {
                matching.push({ name, dist });
            }
        }
        matching.sort((a, b) => a.dist - b.dist);
        const limited = matching.slice(0, 4); // cap at 4 nearest tiles
        console.log(`Tiles within ${maxDistM.toFixed(0)}m: ${matching.length} total, loading ${limited.length} nearest (${limited[0]?.name || 'none'})`);
        return limited.map(m => m.name);
    },

    /**
     * Batch-sample terrain heights for multiple tiles in one Cesium call.
     * Returns a Map of tileName → { center, min }.
     */
    async _batchTerrainSample(viewer, tileNames) {
        const results = new Map();
        const positions = [];
        const tileMap = []; // tracks which positions belong to which tile

        for (const name of tileNames) {
            const info = this.tileIndex.tiles[name];
            if (!info) continue;
            const lat = info.center_lat, lng = info.center_lng;
            const dLat = 256 / 111000;
            const dLng = 256 / (111000 * Math.cos(lat * Math.PI / 180));
            const startIdx = positions.length;
            positions.push(
                Cesium.Cartographic.fromDegrees(lng, lat),
                Cesium.Cartographic.fromDegrees(lng, lat + dLat),
                Cesium.Cartographic.fromDegrees(lng, lat - dLat),
                Cesium.Cartographic.fromDegrees(lng - dLng, lat),
                Cesium.Cartographic.fromDegrees(lng + dLng, lat)
            );
            tileMap.push({ name, startIdx });
        }

        if (positions.length === 0) return results;

        try {
            const terrain = viewer.terrainProvider;
            if (terrain.ready === false) await terrain.readyPromise;
            const updated = await Cesium.sampleTerrainMostDetailed(terrain, positions);
            for (const { name, startIdx } of tileMap) {
                const heights = [];
                for (let i = startIdx; i < startIdx + 5; i++) {
                    heights.push(updated[i].height || 0);
                }
                results.set(name, { center: heights[0], min: Math.min(...heights) });
            }
        } catch (e) {
            console.warn('Batch terrain sampling failed:', e);
            for (const name of tileNames) {
                results.set(name, { center: 0, min: 0 });
            }
        }

        return results;
    },

    /**
     * Load tree 3D Tilesets near a location.
     * Loads nearest 2 tiles first, then the rest in parallel.
     */
    async loadAround(viewer, lat, lng, radiusM) {
        if (!this.tileIndex) await this.loadIndex();

        const tileNames = this.getTilesForLocation(lat, lng, radiusM);
        const toLoad = tileNames.filter(n => !this.loadedTiles.has(n));
        if (toLoad.length === 0) return 0;

        // Batch all terrain sampling in one call (fast)
        const terrainMap = await this._batchTerrainSample(viewer, toLoad);

        // Helper to load + position a single tile (no terrain call needed)
        const loadOne = async (tileName) => {
            if (this.loadedTiles.has(tileName)) return false;
            const tileInfo = this.tileIndex.tiles[tileName];
            if (!tileInfo) return false;
            const terrain = terrainMap.get(tileName) || { center: 0, min: 0 };

            try {
                const tilesetUrl = this.TILE_BASE + tileName + '_tileset.json';
                const tileset = await Cesium.Cesium3DTileset.fromUrl(tilesetUrl, {
                    maximumScreenSpaceError: 16,
                    dynamicScreenSpaceError: false
                });

                tileset.root.transform = Cesium.Matrix4.IDENTITY;
                const center = Cesium.Cartesian3.fromDegrees(
                    tileInfo.center_lng, tileInfo.center_lat,
                    terrain.min + this.heightOffset
                );
                tileset.modelMatrix = Cesium.Transforms.eastNorthUpToFixedFrame(center);
                tileInfo._terrainMin = terrain.min;
                tileInfo._terrainCenter = terrain.center;

                tileset.customShader = new Cesium.CustomShader({
                    fragmentShaderText: `
                        void fragmentMain(FragmentInput fsInput, inout czm_modelMaterial material) {
                        }
                    `
                });

                viewer.scene.primitives.add(tileset);
                this.tilesets.push(tileset);
                this.loadedTiles.add(tileName);
                console.log(`Loaded tree tileset: ${tileName}`);
                return true;
            } catch (e) {
                console.warn(`Failed to load tree tileset ${tileName}:`, e);
                return false;
            }
        };

        let count = 0;

        // Load nearest 2 tiles immediately
        const priority = toLoad.slice(0, 2);
        for (const tileName of priority) {
            if (await loadOne(tileName)) count++;
        }

        // Load remaining tiles in parallel
        const rest = toLoad.slice(2);
        if (rest.length > 0) {
            Promise.all(rest.map(n => loadOne(n))).then(results => {
                const extra = results.filter(Boolean).length;
                if (extra > 0) console.log(`Background: loaded ${extra} more tree tilesets`);
            });
        }

        return count;
    },

    setHeightOffset(offset) {
        this.heightOffset = offset;
        if (!this.tileIndex) return;
        this.tilesets.forEach((ts, i) => {
            const tileName = [...this.loadedTiles][i];
            const tileInfo = this.tileIndex.tiles[tileName];
            if (!tileInfo) return;
            const terrainMin = tileInfo._terrainMin || 0;
            const center = Cesium.Cartesian3.fromDegrees(
                tileInfo.center_lng, tileInfo.center_lat,
                terrainMin + offset
            );
            ts.modelMatrix = Cesium.Transforms.eastNorthUpToFixedFrame(center);
        });
    },

    clear(viewer) {
        for (const ts of this.tilesets) {
            viewer.scene.primitives.remove(ts);
        }
        this.tilesets = [];
        this.loadedTiles.clear();
    }
};
