/**
 * Tree mesh loader — loads pre-generated GLB tree meshes via 3D Tilesets.
 *
 * Tree meshes are generated by extract_scene_dae.py, converted to GLB,
 * and wrapped in tileset.json for correct geopositioning.
 * Each tileset covers one 512m VegLiDAR tile.
 */
const Trees = {
    TILE_BASE: new URLSearchParams(window.location.search).get('tileBase') || 'data/tree_tiles/',
    tileIndex: null,
    loadedTiles: new Set(),
    tilesets: [],
    heightOffset: -6, // meters — compensates for canopy start height + terrain model gap

    TILE_SIZE_M: 512,

    async loadIndex() {
        try {
            const resp = await fetch(this.TILE_BASE + 'index.json');
            this.tileIndex = await resp.json();
            console.log(`Tree tile index: ${Object.keys(this.tileIndex.tiles).length} tiles available`);
            return this.tileIndex;
        } catch (e) {
            console.warn('No tree tile index found — tree meshes not available');
            this.tileIndex = { tiles: {} };
            return this.tileIndex;
        }
    },

    getTilesForLocation(lat, lng, radiusM) {
        if (!this.tileIndex) return [];
        // Filter tiles by distance from search location, sorted nearest-first
        // Each tile covers ~512m, load generously since GLBs are pre-built
        const maxDistM = Math.max(radiusM + 512, 1000);
        const matching = [];
        for (const [name, info] of Object.entries(this.tileIndex.tiles)) {
            const dLat = (info.center_lat - lat) * 111000;
            const dLng = (info.center_lng - lng) * 111000 * Math.cos(lat * Math.PI / 180);
            const dist = Math.sqrt(dLat * dLat + dLng * dLng);
            if (dist < maxDistM) {
                matching.push({ name, dist });
            }
        }
        matching.sort((a, b) => a.dist - b.dist);
        console.log(`Tiles within ${maxDistM.toFixed(0)}m: ${matching.length} (nearest: ${matching[0]?.name || 'none'})`);
        return matching.map(m => m.name);
    },

    /**
     * Sample terrain heights across a tile and return {center, min}.
     * Samples center + 4 edge midpoints to capture terrain variation.
     */
    async getTerrainHeights(viewer, lat, lng) {
        // ~256m offset in degrees (half a 512m tile)
        const dLat = 256 / 111000;
        const dLng = 256 / (111000 * Math.cos(lat * Math.PI / 180));
        const positions = [
            Cesium.Cartographic.fromDegrees(lng, lat),           // center
            Cesium.Cartographic.fromDegrees(lng, lat + dLat),    // N
            Cesium.Cartographic.fromDegrees(lng, lat - dLat),    // S
            Cesium.Cartographic.fromDegrees(lng - dLng, lat),    // W
            Cesium.Cartographic.fromDegrees(lng + dLng, lat),    // E
        ];
        try {
            const terrain = viewer.terrainProvider;
            if (terrain.ready === false) {
                await terrain.readyPromise;
            }
            const updated = await Cesium.sampleTerrainMostDetailed(terrain, positions);
            const heights = updated.map(p => p.height || 0);
            return {
                center: heights[0],
                min: Math.min(...heights)
            };
        } catch (e) {
            console.warn('Terrain sampling failed, using 0:', e);
            return { center: 0, min: 0 };
        }
    },

    /**
     * Load a single tree tileset, position it, and add to scene.
     * Returns true on success, false on failure.
     */
    async _loadTile(viewer, tileName) {
        if (this.loadedTiles.has(tileName)) return false;
        const tileInfo = this.tileIndex.tiles[tileName];
        if (!tileInfo) return false;

        try {
            const tilesetUrl = this.TILE_BASE + tileName + '_tileset.json';
            const tileset = await Cesium.Cesium3DTileset.fromUrl(tilesetUrl, {
                maximumScreenSpaceError: 16,
                dynamicScreenSpaceError: false
            });

            // Sample terrain across the tile to find minimum elevation
            const terrain = await this.getTerrainHeights(
                viewer, tileInfo.center_lat, tileInfo.center_lng
            );
            console.log(`Terrain at ${tileName}: center=${terrain.center.toFixed(1)}m, min=${terrain.min.toFixed(1)}m`);

            // Position mesh origin (Y=0 = z_base) at the lowest terrain point
            tileset.root.transform = Cesium.Matrix4.IDENTITY;
            const center = Cesium.Cartesian3.fromDegrees(
                tileInfo.center_lng, tileInfo.center_lat,
                terrain.min + this.heightOffset
            );
            tileset.modelMatrix = Cesium.Transforms.eastNorthUpToFixedFrame(center);

            tileInfo._terrainMin = terrain.min;
            tileInfo._terrainCenter = terrain.center;

            tileset.customShader = new Cesium.CustomShader({
                fragmentShaderText: `
                    void fragmentMain(FragmentInput fsInput, inout czm_modelMaterial material) {
                        // Pass through vertex colors with no modification
                    }
                `
            });

            viewer.scene.primitives.add(tileset);
            this.tilesets.push(tileset);
            this.loadedTiles.add(tileName);
            console.log(`Loaded tree tileset: ${tileName}`);
            return true;
        } catch (e) {
            console.warn(`Failed to load tree tileset ${tileName}:`, e);
            return false;
        }
    },

    /**
     * Load tree 3D Tilesets near a location.
     * Loads the nearest 2 tiles first (blocking), then the rest in parallel.
     */
    async loadAround(viewer, lat, lng, radiusM) {
        if (!this.tileIndex) await this.loadIndex();

        const tileNames = this.getTilesForLocation(lat, lng, radiusM);
        const toLoad = tileNames.filter(n => !this.loadedTiles.has(n));
        let count = 0;

        // Load nearest 2 tiles immediately (these cover the searched address)
        const priority = toLoad.slice(0, 2);
        for (const tileName of priority) {
            if (await this._loadTile(viewer, tileName)) count++;
        }

        // Load remaining tiles in parallel (non-blocking)
        const rest = toLoad.slice(2);
        if (rest.length > 0) {
            Promise.all(rest.map(n => this._loadTile(viewer, n))).then(results => {
                const extra = results.filter(Boolean).length;
                if (extra > 0) console.log(`Background: loaded ${extra} more tree tilesets`);
            });
        }

        return count;
    },

    setHeightOffset(offset) {
        this.heightOffset = offset;
        // Re-position all loaded tilesets at the new height, relative to terrain
        if (!this.tileIndex) return;
        this.tilesets.forEach((ts, i) => {
            const tileName = [...this.loadedTiles][i];
            const tileInfo = this.tileIndex.tiles[tileName];
            if (!tileInfo) return;
            const terrainMin = tileInfo._terrainMin || 0;
            const center = Cesium.Cartesian3.fromDegrees(
                tileInfo.center_lng, tileInfo.center_lat,
                terrainMin + offset
            );
            ts.modelMatrix = Cesium.Transforms.eastNorthUpToFixedFrame(center);
        });
    },

    clear(viewer) {
        for (const ts of this.tilesets) {
            viewer.scene.primitives.remove(ts);
        }
        this.tilesets = [];
        this.loadedTiles.clear();
    }
};
