/**
 * Tree mesh loader — loads pre-generated GLB tree meshes via 3D Tilesets.
 *
 * Tree meshes are generated by extract_scene_dae.py, converted to GLB,
 * and wrapped in tileset.json for correct geopositioning.
 * Each tileset covers one 512m VegLiDAR tile.
 */
const Trees = {
    TILE_BASE: new URLSearchParams(window.location.search).get('tileBase') || 'data/tree_tiles/',
    tileIndex: null,
    loadedTiles: new Set(),
    tilesets: [],
    heightOffset: -6, // meters — compensates for canopy start height + terrain model gap

    TILE_SIZE_M: 512,

    async loadIndex() {
        try {
            const resp = await fetch(this.TILE_BASE + 'index.json');
            this.tileIndex = await resp.json();
            console.log(`Tree tile index: ${Object.keys(this.tileIndex.tiles).length} tiles available`);
            return this.tileIndex;
        } catch (e) {
            console.warn('No tree tile index found — tree meshes not available');
            this.tileIndex = { tiles: {} };
            return this.tileIndex;
        }
    },

    getTilesForLocation(lat, lng, radiusM) {
        if (!this.tileIndex) return [];
        // Filter tiles by distance from search location
        // Each tile covers ~512m, load generously since GLBs are pre-built
        // Use at least 1000m to ensure good coverage around the search point
        const maxDistM = Math.max(radiusM + 512, 1000);
        const matching = [];
        for (const [name, info] of Object.entries(this.tileIndex.tiles)) {
            const dLat = (info.center_lat - lat) * 111000;
            const dLng = (info.center_lng - lng) * 111000 * Math.cos(lat * Math.PI / 180);
            const dist = Math.sqrt(dLat * dLat + dLng * dLng);
            if (dist < maxDistM) {
                matching.push(name);
            }
        }
        console.log(`Tiles within ${maxDistM.toFixed(0)}m: ${matching.length} of ${Object.keys(this.tileIndex.tiles).length}`);
        return matching;
    },

    /**
     * Sample terrain height at a position using CesiumJS terrain provider.
     */
    async getTerrainHeight(viewer, lat, lng) {
        const positions = [Cesium.Cartographic.fromDegrees(lng, lat)];
        try {
            const terrain = viewer.terrainProvider;
            // Wait for terrain provider to be ready
            if (terrain.ready === false) {
                await terrain.readyPromise;
            }
            const updated = await Cesium.sampleTerrainMostDetailed(terrain, positions);
            return updated[0].height || 0;
        } catch (e) {
            console.warn('Terrain sampling failed, using 0:', e);
            return 0;
        }
    },

    /**
     * Load tree 3D Tilesets near a location.
     * Positions them at terrain height so they sit on the ground.
     */
    async loadAround(viewer, lat, lng, radiusM) {
        if (!this.tileIndex) await this.loadIndex();

        const tileNames = this.getTilesForLocation(lat, lng, radiusM);
        let count = 0;

        for (const tileName of tileNames) {
            if (this.loadedTiles.has(tileName)) continue;

            const tileInfo = this.tileIndex.tiles[tileName];
            if (!tileInfo) continue;

            try {
                const tilesetUrl = this.TILE_BASE + tileName + '_tileset.json';
                const tileset = await Cesium.Cesium3DTileset.fromUrl(tilesetUrl, {
                    maximumScreenSpaceError: 16,
                    dynamicScreenSpaceError: false
                });

                // Sample terrain height at the tile center
                const terrainHeight = await this.getTerrainHeight(
                    viewer, tileInfo.center_lat, tileInfo.center_lng
                );
                console.log(`Terrain height at ${tileName}: ${terrainHeight.toFixed(1)}m`);

                // Override transform using CesiumJS's own ENU math
                // z_base_offset = how far above z_base the center ground is
                // Subtract it so mesh z=0 (z_base) sits at the correct elevation
                const zBaseOffset = tileInfo.z_base_offset || 0;
                tileset.root.transform = Cesium.Matrix4.IDENTITY;
                const center = Cesium.Cartesian3.fromDegrees(
                    tileInfo.center_lng, tileInfo.center_lat,
                    terrainHeight - zBaseOffset + this.heightOffset
                );
                tileset.modelMatrix = Cesium.Transforms.eastNorthUpToFixedFrame(center);

                // Store terrain height for later offset adjustments
                tileInfo._terrainHeight = terrainHeight;

                // Minimal: just pass through natural LiDAR + classification colors
                tileset.customShader = new Cesium.CustomShader({
                    fragmentShaderText: `
                        void fragmentMain(FragmentInput fsInput, inout czm_modelMaterial material) {
                            // Pass through vertex colors with no modification
                        }
                    `
                });

                viewer.scene.primitives.add(tileset);
                this.tilesets.push(tileset);
                this.loadedTiles.add(tileName);
                count++;
                console.log(`Loaded tree tileset: ${tileName}`);
            } catch (e) {
                console.warn(`Failed to load tree tileset ${tileName}:`, e);
            }
        }
        return count;
    },

    setHeightOffset(offset) {
        this.heightOffset = offset;
        // Re-position all loaded tilesets at the new height, relative to terrain
        if (!this.tileIndex) return;
        this.tilesets.forEach((ts, i) => {
            const tileName = [...this.loadedTiles][i];
            const tileInfo = this.tileIndex.tiles[tileName];
            if (!tileInfo) return;
            const terrainHeight = tileInfo._terrainHeight || 0;
            const zBaseOffset = tileInfo.z_base_offset || 0;
            const center = Cesium.Cartesian3.fromDegrees(
                tileInfo.center_lng, tileInfo.center_lat,
                terrainHeight - zBaseOffset + offset
            );
            ts.modelMatrix = Cesium.Transforms.eastNorthUpToFixedFrame(center);
        });
    },

    clear(viewer) {
        for (const ts of this.tilesets) {
            viewer.scene.primitives.remove(ts);
        }
        this.tilesets = [];
        this.loadedTiles.clear();
    }
};
